include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - test/**
    - lib/app/localization/generated/**
    - lib/app/utils/network/**
    - '**.g.dart'
  language:
    strict-casts: true
    strict-raw-types: true
  errors:
    missing_required_param: warning
    missing_return: warning
    todo: ignore
  plugins:
    - dart_code_metrics

dart_code_metrics:
  anti-patterns:
    - long-method
    - long-parameter-list
  metrics:
    cyclomatic-complexity: 20
    maximum-nesting-level: 5
    number-of-parameters: 4
    source-lines-of-code: 50
  metrics-exclude:
    - test/**
    - lib/utils/**
    - lib/app/navigation/**
    - '**.g.dart'
  rules:
    - newline-before-return
    - no-boolean-literal-compare
    - always-remove-listener
    - avoid-wrapping-in-padding
    - avoid-border-all
    - avoid-unnecessary-setstate
    - avoid-expanded-as-spacer
    - avoid-returning-widgets
    - avoid-shrink-wrap-in-lists
    - avoid-cascade-after-if-null
    - avoid-collection-methods-with-unrelated-types
    - avoid-double-slash-imports
    - avoid-duplicate-exports
    - avoid-dynamic
    - avoid-global-state
    - avoid-nested-conditional-expressions
    - avoid-non-null-assertion
    - avoid-throw-in-catch-block
    - avoid-unnecessary-conditionals
    - avoid-unnecessary-type-assertions
    - avoid-unnecessary-type-casts
    - avoid-unrelated-type-assertions
    - avoid-unused-parameters
    - binary-expression-operand-order
    - double-literal-format
    - format-comment
    - prefer-trailing-comma
    - prefer-conditional-expressions
    - prefer-const-border-radius
    - prefer-single-widget-per-file
    - prefer-correct-edge-insets-constructor
    - prefer-using-list-view
    - prefer-async-await
    - prefer-correct-type-name
    - prefer-enums-by-name
    - prefer-match-file-name:
        exclude:
          - test/**
          - lib/main.dart
          - lib/app/utils/extensions.dart
          - lib/app/navigation/navigation_helpers.dart
    - prefer-moving-to-variable
    - prefer-trailing-comma
    - prefer-immediate-return
    - prefer-iterable-of
    - no-equal-then-else
    - use-setstate-synchronously
    - member-ordering:
        order:
          - constructors
          - public-fields
          - private-fields
          - close-method
          - dispose-method
        widgets-order:
          - constructors
          - public-fields
          - private-fields
          - init-state-method
          - build-method
          - overridden-public-methods
          - private-methods

linter:
  rules:
    prefer_single_quotes: true
    prefer_relative_imports: true
    avoid_returning_null_for_future: true
    avoid_slow_async_io: true
    literal_only_boolean_expressions: true
    throw_in_finally: true
    unnecessary_statements: true
    always_declare_return_types: true
    always_put_control_body_on_new_line: true
    always_put_required_named_parameters_first: true
    avoid_bool_literals_in_conditional_expressions: true
    avoid_catches_without_on_clauses: true
    avoid_field_initializers_in_const_classes: true
    avoid_multiple_declarations_per_line: true
    avoid_positional_boolean_parameters: true
    avoid_redundant_argument_values: true
    avoid_returning_null: true
    avoid_returning_null_for_void: true
    avoid_unused_constructor_parameters: true
    avoid_void_async: true
    cascade_invocations: true
    curly_braces_in_flow_control_structures: true
    deprecated_consistency: true
    directives_ordering: true
    eol_at_end_of_file: true
    join_return_with_assignment: true
    lines_longer_than_80_chars: true
    missing_whitespace_between_adjacent_strings: true
    no_leading_underscores_for_library_prefixes: true
    no_leading_underscores_for_local_identifiers: true
    null_check_on_nullable_type_parameter: true
    one_member_abstracts: true
    only_throw_errors: true
    parameter_assignments: true
    prefer_expression_function_bodies: false
    prefer_final_locals: true
    prefer_if_elements_to_conditional_expressions: true
    prefer_interpolation_to_compose_strings: true
    prefer_null_aware_method_calls: true
    sized_box_shrink_expand: true
    sort_child_properties_last: true
    sort_unnamed_constructors_first: true
    sort_constructors_first: true
    unawaited_futures: true
    unnecessary_constructor_name: true
    unnecessary_lambdas: true
    unnecessary_late: true
    unnecessary_null_aware_assignments: true
    unnecessary_parenthesis: true
    unnecessary_raw_strings: true
    use_colored_box: true
    use_decorated_box: true
    use_if_null_to_convert_nulls_to_bools: true
    use_is_even_rather_than_modulo: true
    use_named_constants: true
    use_to_and_as_if_applicable: true
    require_trailing_commas: true
    use_enums: true
    use_full_hex_values_for_flutter_colors: true
    use_rethrow_when_possible: true
    use_key_in_widget_constructors: true
    use_super_parameters: true
    always_require_non_null_named_parameters: true
    annotate_overrides: true
    avoid_catching_errors: true
    avoid_classes_with_only_static_members: true
    avoid_empty_else: true
    avoid_escaping_inner_quotes: true
    avoid_function_literals_in_foreach_calls: true
    avoid_implementing_value_types: true
    avoid_init_to_null: true
    avoid_null_checks_in_equality_operators: true
    avoid_print: true
    avoid_private_typedef_functions: true
    avoid_relative_lib_imports: true
    avoid_return_types_on_setters: true
    avoid_setters_without_getters: true
    avoid_shadowing_type_parameters: true
    avoid_single_cascade_in_expression_statements: true
    avoid_type_to_string: true
    avoid_types_as_parameter_names: true
    avoid_unnecessary_containers: true
    avoid_web_libraries_in_flutter: true
    await_only_futures: true
    camel_case_extensions: true
    camel_case_types: true
    cancel_subscriptions: true
    cast_nullable_to_non_nullable: true
    constant_identifier_names: true
    control_flow_in_finally: true
    depend_on_referenced_packages: true
    empty_catches: true
    empty_constructor_bodies: true
    empty_statements: true
    exhaustive_cases: true
    file_names: true
    hash_and_equals: true
    implementation_imports: true
    collection_methods_unrelated_type: true
    leading_newlines_in_multiline_strings: true
    library_names: true
    library_prefixes: true
    no_adjacent_strings_in_list: true
    no_duplicate_case_values: true
    no_logic_in_create_state: true
    no_runtimeType_toString: true
    non_constant_identifier_names: true
    noop_primitive_operations: true
    null_closures: true
    overridden_fields: true
    package_names: true
    package_prefixed_library_names: true
    prefer_asserts_in_initializer_lists: true
    prefer_collection_literals: true
    prefer_conditional_assignment: true
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    prefer_constructors_over_static_methods: true
    prefer_contains: true
    prefer_final_fields: true
    prefer_final_in_for_each: true
    prefer_for_elements_to_map_fromIterable: true
    prefer_function_declarations_over_variables: true
    prefer_generic_function_type_aliases: true
    prefer_if_null_operators: true
    prefer_initializing_formals: true
    prefer_inlined_adds: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_is_not_operator: true
    prefer_iterable_whereType: true
    prefer_spread_collections: true
    prefer_typing_uninitialized_variables: true
    prefer_void_to_null: true
    provide_deprecation_message: true
    recursive_getters: true
    sized_box_for_whitespace: true
    slash_for_doc_comments: true
    test_types_in_equals: true
    tighten_type_of_initializing_formals: true
    type_annotate_public_apis: true
    type_init_formals: true
    unnecessary_await_in_return: true
    unnecessary_brace_in_string_interps: true
    unnecessary_const: true
    unnecessary_getters_setters: true
    unnecessary_new: true
    unnecessary_null_checks: true
    unnecessary_null_in_if_null_operators: true
    unnecessary_nullable_for_final_variable_declarations: true
    unnecessary_overrides: true
    unnecessary_string_escapes: true
    unnecessary_string_interpolations: true
    unnecessary_this: true
    unrelated_type_equality_checks: true
    unsafe_html: true
    use_build_context_synchronously: true
    use_function_type_syntax_for_parameters: true
    use_late_for_private_fields_and_variables: true
    use_setters_to_change_properties: true
    use_string_buffers: true
    use_test_throws_matchers: true
    valid_regexps: true
    void_checks: true