#!/bin/bash

PROJECT_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
MAIN_FLUTTER_PACKAGE="$(./main_package)"

if [ "$MAIN_FLUTTER_PACKAGE" != "." ]; then
  mv "$MAIN_FLUTTER_PACKAGE/build" "$PROJECT_ROOT"
fi
