#!/bin/bash

flutter config --android-sdk /opt/android

# Export Variables
export ORG_GRADLE_PROJECT_keyStore=$BITBUCKET_CLONE_DIR/keystore.jks
export ORG_GRADLE_PROJECT_keyStorePassword=$KEYSTORE_PASSWORD
export ORG_GRADLE_PROJECT_alias=$KEYSTORE_ALIAS
export ORG_GRADLE_PROJECT_keyPass=$KEY_PASSWORD
